In [ ]:
import pandas as pd

df_features = pd.read_csv(r'C:\Users\User\gpr\simulação\sim1\Features.csv')
df_labels = pd.read_csv(r'C:\Users\User\gpr\simulação\sim1\labels.csv')

df_features = df_features.merge(df_labels,right_index=True,left_index=True)
display(df_features)

df_features.to_csv('Dados completos.csv', index=False)

df_features.to_csv(
    'Dados completos.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

df_com_cilindro = df_features[df_features['Label'] == 1]
df_sem_cilindro = df_features[df_features['Label'] == 0]
display(df_com_cilindro.describe())
display(df_sem_cilindro.describe())

,Média,Variância,Máximo,Energia,Skewness,Kurtosis,Label
0,-8.118985,5046.064678,426.044495,1.953800e+08,-1.530590,8.882906,1
1,-7.001265,2914.390897,319.997040,1.132615e+08,-0.170471,5.186916,1
2,-8.304564,4730.422292,412.039764,1.834326e+08,0.062562,6.203662,1
3,-6.039109,3363.004739,359.805054,1.299280e+08,0.507617,7.962693,1
4,-4.586327,2934.315264,322.917328,1.129535e+08,0.762987,6.374970,1
...,...,...,...,...,...,...,...
995,-8.251102,2303.713750,518.999451,9.064998e+07,-3.670779,23.739924,0
996,-9.545670,1490.886697,257.687439,6.046429e+07,-2.448785,8.366446,0
997,-7.151956,5610.206699,384.289520,2.163771e+08,0.213659,6.120610,1
998,-8.500808,2158.034073,248.050430,8.524198e+07,-1.234216,5.871989,0
999,-8.509017,1807.065572,302.602753,7.183330e+07,-2.078960,9.192381,0

,Média,Variância,Máximo,Energia,Skewness,Kurtosis,Label
count,503.000000,503.000000,503.000000,5.030000e+02,503.000000,503.000000,503.0
mean,-7.565925,3537.142007,338.738762,1.375151e+08,-0.214168,6.108387,1.0
std,1.900248,1140.186190,60.597295,4.359530e+07,0.659660,1.941094,0.0
min,-13.533509,1302.958999,201.241730,5.464023e+07,-2.461867,2.282273,1.0
25%,-8.804095,2681.342613,296.080124,1.045778e+08,-0.632936,4.645785,1.0
50%,-7.528597,3397.709548,332.707062,1.325705e+08,-0.170953,5.875279,1.0
75%,-6.247068,4215.175628,375.810913,1.634613e+08,0.218934,7.255139,1.0
max,-1.662538,7593.830016,554.253479,2.929905e+08,1.797384,12.352577,1.0

,Média,Variância,Máximo,Energia,Skewness,Kurtosis,Label
count,497.000000,497.000000,497.000000,4.970000e+02,497.000000,497.000000,497.0
mean,-9.183955,2011.034088,333.836725,8.014002e+07,-2.280561,10.389611,0.0
std,1.196781,632.803326,66.386883,2.444625e+07,0.657876,3.980963,0.0
min,-12.690229,814.085328,177.801468,3.272571e+07,-4.200733,3.095921,0.0
25%,-10.033144,1558.646361,288.213470,6.299467e+07,-2.737675,7.599084,0.0
50%,-9.207935,1874.970271,327.675110,7.491772e+07,-2.274281,9.643918,0.0
75%,-8.358135,2343.092291,367.889557,9.306606e+07,-1.803369,12.370628,0.0
max,-5.877437,6258.747970,625.424255,2.445004e+08,-0.645640,26.538381,0.0